_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
accelerator: gpu
devices: auto

min_epochs: 5
max_epochs: null
reload_dataloaders_every_n_epochs: 1
num_sanity_val_steps: 0
fast_dev_run: false
profiler: 'simple'

accumulate_grad_batches: 4
val_check_interval: 8000
limit_val_batches: 800
log_every_n_steps: 50


