_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 0
auto_select_gpus: False

min_epochs: 1
max_epochs: 10

resume_from_checkpoint: null
fast_dev_run: false
profiler: 'simple'
