name: predict_pv_yield
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - matplotlib
  - zarr
  - xarray
  - ipykernel
  - google-cloud-storage
  - gcsfs
  - dask
  - python-graphviz  # used for visualising dask graphs
  - conda-forge::opencv  # also run `apt install libgl1-mesa-glx`
  - scikit-image
  - pytorch::pytorch  # explicitly specify pytorch channel to prevent conda from using conda-forge for pytorch, and hence installing the CPU-only version.
  - cudatoolkit=11.0
  - pytorch::torchvision
  - pytorch-lightning
