name: predict_pv_yield
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - matplotlib
  - zarr
  - xarray
  - ipykernel
  - google-cloud-storage
  - gcsfs
  - dask
  - python-graphviz  # used for visualising dask graphs
  - opencv  # also run `apt install libgl1-mesa-glx`
  - scikit-image
  - pytorch
  - cudatoolkit=11.0
  - pytorch-lightning
