name: predict_pv_yield
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9
  - pip

  # Scientific Python
  - numpy
  - pandas
  - matplotlib
  - xarray
  - ipykernel
  - pyproj
  - h5netcdf

  # Cloud & distributed compute
  - gcsfs

  # Machine learning
  - pytorch::pytorch  # explicitly specify pytorch channel to prevent conda from using conda-forge for pytorch, and hence installing the CPU-only version.
  - pytorch-lightning

  # Development tools
  - pytest
  - flake8
  - jedi
  - mypy

  - pip:
    - neptune-client[pytorch-lightning]
    - tilemapbase  # For plotting human-readable geographical maps.
    - perceiver-pytorch
