_target_: pvnet.models.conv3d.model_sat_nwp.Model

# Sat/NWP encoder settings
image_encoder: 
    _target_: pvnet.models.conv3d.encoders.EncoderNaiveEfficientNet
    _partial_: True

encoder_out_features: 128
encoder_kwargs: 
    model_name: efficientnet-b0

include_nwp: True
sat_image_size_pixels: 24
nwp_image_size_pixels: 24
number_sat_channels: 11
number_nwp_channels: 2

# Tabular network settings
output_network: 
    _target_: pvnet.models.conv3d.dense_networks.TabNet
    _partial_: True
output_network_kwrgs:
        # Dimension of the prediction  layer (usually between 4 and 64)
        n_d : 8
        # Dimension of the attention  layer (usually between 4 and 64)
        n_a : 8
        # Number of successive steps in the network (usually between 3 and 10)
        n_steps : 3
        # Float above 1, scaling factor for attention updates (usually between 1.0 to 2.0)
        gamma : 1.3
        # Number of independent GLU layer in each GLU block (default 2)
        n_independent : 2
        # Number of independent GLU layer in each GLU block (default 2)
        n_shared : 2
        # Batch size for Ghost Batch Normalization
        virtual_batch_size : 32
        # Float value between 0 and 1 which will be used for momentum in all batch norm
        momentum : 0.02
        #  Either "sparsemax" or "entmax" : this is the masking function to use
        mask_type : sparsemax

embedding_dim: 16
include_sun: True
include_gsp_yield_history: True

# Foreast and time settings
forecast_minutes: 480
history_minutes: 120
# --- set to null if same as history_minutes ---
sat_history_minutes: 90
nwp_history_minutes: 120
nwp_forecast_minutes: 480
# ----------------------------------------------
