_target_: pvnet.models.conv3d.model_sat_nwp.Model

include_pv_or_gsp_yield_history: True
include_nwp: True
forecast_minutes: 480
history_minutes: 60
number_of_conv3d_layers: 6
image_size_pixels: 24
number_sat_channels: 11
number_nwp_channels: 2
conv3d_channels: 32
fc1_output_features: 128
fc2_output_features: 128
fc3_output_features: 64
output_variable: gsp_yield
include_pv_yield_history: False
include_future_satellite: False
