_target_: pvnet.models.conv3d.model_sat_nwp.Model

# Sat/NWP encoder settings
image_encoder: 
    _target_: pvnet.models.conv3d.encoders.EncoderNaiveEfficientNet
    _partial_: True

encoder_out_features: 128
encoder_kwargs: 
    model_name: efficientnet-b0

include_nwp: True
sat_image_size_pixels: 24
nwp_image_size_pixels: 24
number_sat_channels: 11
number_nwp_channels: 2

# Tabular network settings
output_network: 
    _target_: pvnet.models.conv3d.dense_networks.DefaultFCNet
    _partial_: True
output_network_kwrgs:
    fc_hidden_features: 64

embedding_dim: 16
include_sun: True
include_gsp_yield_history: True

# Foreast and time settings
forecast_minutes: 480
history_minutes: 120
# --- set to null if same as history_minutes ---
sat_history_minutes: 90
nwp_history_minutes: 120
nwp_forecast_minutes: 480
# ----------------------------------------------
