_target_: predict_pv_yield.models.conv3d.model_nwp.Model

include_pv_or_gsp_yield_history: True
forecast_minutes: 120
history_minutes: 30
number_of_conv3d_layers: 6
conv3d_channels: 32
fc1_output_features: 128
fc2_output_features: 128
fc3_output_features: 64
number_nwp_channels: 1

