_target_: predict_pv_yield.models.conv3d.model.Model

include_pv_yield: False
include_nwp: False
forecast_len: 6
history_len: 12
number_of_conv3d_layers: 4
conv3d_channels: 32
image_size_pixels: 64
number_sat_channels: 12
batch_size: 64