_target_: pvnet.models.multimodal.multimodal.Model

output_quantiles: null

#--------------------------------------------
# NWP encoder
#--------------------------------------------

nwp_encoder:
  _target_: pvnet.models.multimodal.encoders.encoders3d.DefaultPVNet
  _partial_: True
  in_channels: 2
  out_features: 256
  number_of_conv3d_layers: 6
  conv3d_channels: 32
  image_size_pixels: 24

#--------------------------------------------
# Sat encoder settings
#--------------------------------------------

sat_encoder:
  _target_: pvnet.models.multimodal.encoders.encoders3d.DefaultPVNet
  _partial_: True
  in_channels: 11
  out_features: 256
  number_of_conv3d_layers: 6
  conv3d_channels: 32
  image_size_pixels: 24

add_image_embedding_channel: True

#--------------------------------------------
# PV encoder settings
#--------------------------------------------

pv_encoder:
  _target_: pvnet.models.multimodal.site_encoders.encoders.SimpleLearnedAggregator
  _partial_: True
  out_features: 256
  num_sites: 349


#--------------------------------------------
# Tabular network settings
#--------------------------------------------

output_network:
  _target_: pvnet.models.multimodal.linear_networks.networks.ResFCNet2
  _partial_: True
  fc_hidden_features: 128
  n_res_blocks: 6
  res_block_layers: 2
  dropout_frac: 0.0

embedding_dim: 16
include_sun: True
include_gsp_yield_history: True

#--------------------------------------------
# Times
#--------------------------------------------

# Foreast and time settings
forecast_minutes: 480
history_minutes: 120
# --- set to null if same as history_minutes ---
sat_history_minutes: 90
nwp_history_minutes: 120
nwp_forecast_minutes: 480
pv_history_minutes: 180

# ----------------------------------------------
# Optimizer
# ----------------------------------------------
optimizer:
  _target_: pvnet.optimizers.AdamWReduceLROnPlateau
  lr: 0.0001
  weight_decay: 0.25
  amsgrad: True
  patience: 5
  factor: 0.1
  threshold: 0.002
