_target_: predict_pv_yield.data.dataloader.NetCDFDataModule

temp_path: "."
n_train_data: 24900
n_val_data: 1000
cloud:  "gcp"
num_workers: 8
pin_memory: True
data_path: "gs://solar-pv-nowcasting-data/prepared_ML_training_data/v4/"
fake_data: False
