_target_: predict_pv_yield.data.dataloader.NetCDFDataModule

temp_path: "."
n_train_data: 24900
n_val_data: 1000
cloud:  "local"
num_workers: 8
pin_memory: True
data_path: "/mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v14/"
fake_data: False
