_target_: ocf_datapipes.training.datamodules.default.DataModule

data_pipeline: "gsp_pv_satellite_nwp"
#defaults:
#  - configuration: local_configuration.yaml
configuration: "/home/james/repos/PVNet/configs/datamodule/configuration/local_configuration.yaml"
n_train_data: 4000
n_val_data: 400
#num_workers: 2
#pin_memory: True
#data_path: "/mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v15/"
fake_data: False
#shuffle_train: True
