_target_: ocf_datapipes.training.datamodules.default.DataModule

data_pipeline: "gsp_pv_satellite_nwp"
#defaults:
#  - configuration: local_configuration.yaml
configuration: "/home/jamesfulton/repos/PVNet/configs/datamodule/configuration/gcp_configuration.yaml"
fake_data: False
n_train_data: 4000
n_val_data: 400
num_workers: 2
prefetch_factor: 2
