_target_: pvnet.data.wind_datamodule.WindDataModule
configuration: "/home/jacob/PVNet/configs/datamodule/configuration/leonardo_pv_configuration.yaml"
num_workers: 1
prefetch_factor: 2
batch_size: 8
batch_dir: "/mnt/storage_ssd_4tb/windnet_batches"
train_period:
  - 2022-01-01
  - 2022-09-29
val_period:
  - 2022-09-30
  - 2022-12-31
test_period:
  - 2022-09-01
  - 2022-12-31
