_target_: pvnet.data.datamodule.DataModule
configuration: "/home/jamesfulton/repos/PVNet/configs/datamodule/configuration/gcp_configuration.yaml"
use_premade_batches: True
batch_dir: "/mnt/disks/batches/batches_v1"
num_workers: 10
prefetch_factor: 2
batch_size: 8
train_period:
    - null
    - 2020-12-31
val_period:
    - 2021-01-01
    - 2021-12-31
test_period:
    - 2021-01-01
    - 2021-12-31