general:
  description: Template including all possible settings
  name: template

input_data:
  default_forecast_minutes: 120
  default_history_minutes: 60

  gsp:
    gsp_zarr_path: gs://solar-pv-nowcasting-data/PV/GSP/v7/pv_gsp.zarr
    history_minutes: 60
    forecast_minutes: 120
    time_resolution_minutes: 30
    start_datetime: "2020-01-01T00:00:00"
    end_datetime: "2021-09-01T00:00:00"

  nwp:
    ukv:
      nwp_zarr_path: gs://solar-pv-nowcasting-data/NWP/UK_Met_Office/UKV_intermediate_version_7.zarr
      history_minutes: 60
      forecast_minutes: 120
      time_resolution_minutes: 60
      nwp_channels: # comment out channels as appropriate
        - t # 2-metre temperature
        - dswrf # downwards short-wave radiation flux
        - dlwrf # downwards long-wave radiation flux
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - vis # visability
        - r # relative humidity
        - prate # precipitation rate
        - si10 # 10-metre wind speed | live = unknown
      nwp_image_size_pixels_height: 24
      nwp_image_size_pixels_width: 24
      nwp_provider: ukv
      start_datetime: "2020-01-01T00:00:00"
      end_datetime: "2021-09-01T00:00:00"

  pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: gs://solar-pv-nowcasting-data/PV/Passive/ocf_formatted/v0/passiv.netcdf
        pv_metadata_filename: gs://solar-pv-nowcasting-data/PV/Passive/ocf_formatted/v0/system_metadata_OCF_ONLY.csv
        # This is the list of pv_ml_ids to be sliced from the PV site level data
    pv_ml_ids:
      [
        154,
        155,
        156,
        158,
        159,
        160,
        162,
        164,
        165,
        166,
        167,
        168,
        169,
        171,
        173,
        177,
        178,
        179,
        181,
        182,
        185,
        186,
        187,
        188,
        189,
        190,
        191,
        192,
        193,
        197,
        198,
        199,
        200,
        202,
        204,
        205,
        206,
        208,
        209,
        211,
        214,
        215,
        216,
        217,
        218,
        219,
        220,
        221,
        225,
        229,
        230,
        232,
        233,
        234,
        236,
        242,
        243,
        245,
        252,
        254,
        255,
        256,
        257,
        258,
        260,
        261,
        262,
        265,
        267,
        268,
        272,
        273,
        275,
        276,
        277,
        280,
        281,
        282,
        283,
        287,
        289,
        291,
        292,
        293,
        294,
        295,
        296,
        297,
        298,
        301,
        302,
        303,
        304,
        306,
        307,
        309,
        310,
        311,
        317,
        318,
        319,
        320,
        321,
        322,
        323,
        325,
        326,
        329,
        332,
        333,
        335,
        336,
        338,
        340,
        342,
        344,
        345,
        346,
        348,
        349,
        352,
        354,
        355,
        356,
        357,
        360,
        362,
        363,
        368,
        369,
        370,
        371,
        372,
        374,
        375,
        376,
        378,
        380,
        382,
        384,
        385,
        388,
        390,
        391,
        393,
        396,
        397,
        398,
        399,
        400,
        401,
        403,
        404,
        405,
        406,
        407,
        409,
        411,
        412,
        413,
        414,
        415,
        416,
        417,
        418,
        419,
        420,
        421,
        422,
        423,
        424,
        425,
        426,
        427,
        429,
        431,
        435,
        437,
        438,
        440,
        441,
        444,
        447,
        450,
        451,
        453,
        456,
        457,
        458,
        459,
        464,
        465,
        466,
        467,
        468,
        470,
        471,
        473,
        474,
        476,
        477,
        479,
        480,
        481,
        482,
        485,
        486,
        488,
        490,
        491,
        492,
        493,
        496,
        498,
        501,
        503,
        506,
        507,
        508,
        509,
        510,
        511,
        512,
        513,
        515,
        516,
        517,
        519,
        520,
        521,
        522,
        524,
        526,
        527,
        528,
        531,
        532,
        536,
        537,
        538,
        540,
        541,
        542,
        543,
        544,
        545,
        549,
        550,
        551,
        552,
        553,
        554,
        556,
        557,
        560,
        561,
        563,
        566,
        568,
        571,
        572,
        575,
        576,
        577,
        579,
        580,
        581,
        582,
        584,
        585,
        588,
        590,
        594,
        595,
        597,
        600,
        602,
        603,
        604,
        606,
        611,
        613,
        614,
        616,
        618,
        620,
        622,
        623,
        624,
        625,
        626,
        628,
        629,
        630,
        631,
        636,
        637,
        638,
        640,
        641,
        642,
        644,
        645,
        646,
        650,
        651,
        652,
        653,
        654,
        655,
        657,
        660,
        661,
        662,
        663,
        666,
        667,
        668,
        670,
        675,
        676,
        679,
        681,
        683,
        684,
        685,
        687,
        696,
        698,
        701,
        702,
        703,
        704,
        706,
        710,
        722,
        723,
        724,
        725,
        727,
        728,
        729,
        730,
        732,
        733,
        734,
        735,
        736,
        737,
      ]
    history_minutes: 60
    forecast_minutes: 120
    time_resolution_minutes: 5
    start_datetime: "2020-01-01T00:00:00"
    end_datetime: "2021-09-01T00:00:00"
    pv_image_size_meters_height: 24
    pv_image_size_meters_width: 24
    n_pv_systems_per_example: 128
    get_center: false
    is_live: false

  satellite:
    satellite_zarr_path:
      - "gs://public-datasets-eumetsat-solar-forecasting/satellite/EUMETSAT/SEVIRI_RSS/v4/2020_nonhrv.zarr"
      - "gs://public-datasets-eumetsat-solar-forecasting/satellite/EUMETSAT/SEVIRI_RSS/v4/2021_nonhrv.zarr"
    history_minutes: 60
    forecast_minutes: 0
    live_delay_minutes: 30
    time_resolution_minutes: 5
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels_height: 24
    satellite_image_size_pixels_width: 24
