general:
  description: Template including all possible settings
  name: template

input_data:
  default_forecast_minutes: 120
  default_history_minutes: 60

  gsp:
    gsp_zarr_path: gs://solar-pv-nowcasting-data/PV/GSP/v7/pv_gsp.zarr
    history_minutes: 60
    forecast_minutes: 120
    time_resolution_minutes: 30
    start_datetime: "2020-01-01T00:00:00"
    end_datetime: "2021-09-01T00:00:00"

  nwp:
    ukv:
      nwp_zarr_path: gs://solar-pv-nowcasting-data/NWP/UK_Met_Office/UKV_intermediate_version_7.zarr
      history_minutes: 60
      forecast_minutes: 120
      time_resolution_minutes: 60
      nwp_channels: # comment out channels as appropriate
        - t # 2-metre temperature
        - dswrf # downwards short-wave radiation flux
        - dlwrf # downwards long-wave radiation flux
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - vis # visability
        - r # relative humidity
        - prate # precipitation rate
        - si10 # 10-metre wind speed | live = unknown
      nwp_image_size_pixels_height: 24
      nwp_image_size_pixels_width: 24
      nwp_provider: ukv
      start_datetime: "2020-01-01T00:00:00"
      end_datetime: "2021-09-01T00:00:00"

  pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: gs://solar-pv-nowcasting-data/PV/Passive/ocf_formatted/v0/passiv.netcdf
        pv_metadata_filename: gs://solar-pv-nowcasting-data/PV/Passive/ocf_formatted/v0/system_metadata_OCF_ONLY.csv
        # This is the list of pv_ml_ids to be sliced from the PV site level data
    pv_ml_ids:
      [
        156,
        158,
        159,
        160,
        162,
      ]
    history_minutes: 60
    forecast_minutes: 120
    time_resolution_minutes: 5
    start_datetime: "2020-01-01T00:00:00"
    end_datetime: "2021-09-01T00:00:00"
    pv_image_size_meters_height: 24
    pv_image_size_meters_width: 24
    n_pv_systems_per_example: 128
    get_center: false
    is_live: false

  satellite:
    satellite_zarr_path:
      - "gs://public-datasets-eumetsat-solar-forecasting/satellite/EUMETSAT/SEVIRI_RSS/v4/2020_nonhrv.zarr"
      - "gs://public-datasets-eumetsat-solar-forecasting/satellite/EUMETSAT/SEVIRI_RSS/v4/2021_nonhrv.zarr"
    history_minutes: 60
    forecast_minutes: 0
    live_delay_minutes: 30
    time_resolution_minutes: 5
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels_height: 24
    satellite_image_size_pixels_width: 24
