# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "/mnt/disks/batches/tensorboard"
  name: "default"
  version: "${model_name}"
  log_graph: False
  default_hp_metric: False
  prefix: ""
