general:
  description: WindNet configuration for Leonardo
  name: windnet_india

input_data:
  default_forecast_minutes: 480
  default_history_minutes: 60
  data_source_which_defines_geospatial_locations: "sensor"
  nwp:
    nwp_zarr_path: "/mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/NWP/ECMWF/nw-india/zarr/2022*.zarr.zip"
    history_minutes: 60
    forecast_minutes: 480
    time_resolution_minutes: 60
    nwp_channels:
      - hcc
      - lcc
      - mcc
      - prate
      - sde
      - sr
      - t2m
      - tcc
      - u10
      - u100
      - u200
      - v10
      - v100
      - v200
    nwp_image_size_pixels_height: 16
    nwp_image_size_pixels_width: 16
    x_dim_name: "longitude"
    y_dim_name: "latitude"
    nwp_provider: "ecmwf"
  sensor:
    sensor_filename: "/mnt/storage_ssd_4tb/ASOS/asos_india_new_all_nw_india.nc"
    sensor_variables:
      - wind_speed_knots
    x_dim_name: "longitude"
    y_dim_name: "latitude"
