general:
  description: WindNet configuration for Leonardo
  name: windnet_india

input_data:
  default_forecast_minutes: 1440
  default_history_minutes: 60
  data_source_which_defines_geospatial_locations: "wind"
  nwp:
    ecmwf:
      # Path to ECMWF NWP data in zarr format
      # n.b. It is not necessary to use multiple or any NWP data. These entries can be removed
      nwp_zarr_path: "/mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/NWP/ECMWF/nw-india/zarr/2022*.zarr.zip"
      history_minutes: 60
      forecast_minutes: 1440
      time_resolution_minutes: 60
      nwp_channels:
        - hcc
        - lcc
        - mcc
        - prate
        - sde
        - sr
        - t2m
        - tcc
        - u10
        - u100
        - u200
        - v10
        - v100
        - v200
      nwp_image_size_pixels_height: 16 # roughtly equivalent to ukv 24 pixels
      nwp_image_size_pixels_width: 16
      x_dim_name: "longitude"
      y_dim_name: "latitude"
      nwp_provider: "ecmwf"
      start_datetime: "2021-01-01 00:00:00"
      end_datetime: "2024-01-01 00:00:00"
  wind:
    wind_files_groups:
      - label: india
        wind_filename: /mnt/storage_ssd_4tb/india_wind_data.nc
        wind_metadata_filename: /mnt/storage_ssd_4tb/india_wind_metadata.csv
    get_center: true
    n_wind_systems_per_example: 1
    start_datetime: "2021-01-01 00:00:00"
    end_datetime: "2024-01-01 00:00:00"
