general:
  description: Template including all settings
  name: template

input_data:
  data_source_which_defines_geospatial_locations: gsp
  default_forecast_minutes: 120
  default_history_minutes: 60

  gsp:
    gsp_zarr_path: gs://solar-pv-nowcasting-data/PV/GSP/v5/pv_gsp.zarr
    history_minutes: 60
    forecast_minutes: 120
    time_resolution_minutes: 30
    start_datetime: "2020-01-01T00:00:00"
    end_datetime: "2021-09-01T00:00:00"
    gsp_image_size_pixels_height: 64
    gsp_image_size_pixels_width: 64
    gsp_meters_per_pixel: 2000
    n_gsp_per_example: 32
    is_live: false
    live_interpolate_minutes: 60
    live_load_extra_minutes: 60
    log_level: ERROR
    metadata_only: false

  nwp:
    nwp_zarr_path: gs://solar-pv-nowcasting-data/NWP/UK_Met_Office/UKV_intermediate_version_7.zarr
    history_minutes: 60
    forecast_minutes: 120
    time_resolution_minutes: 60
    nwp_channels:
      - t # live = t2m
      - dswrf
      - dlwrf
      - hcc
      - mcc
      - lcc
      - vis
      - r # live = r2
      - prate # live ~= rprate
      - si10 # 10-metre wind speed | live = unknown
    nwp_image_size_pixels_height: 24
    nwp_image_size_pixels_width: 24
    nwp_meters_per_pixel: 2000
    log_level: DEBUG

  pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: gs://solar-pv-nowcasting-data/PV/Passive/ocf_formatted/v0/passiv.netcdf
        pv_metadata_filename: gs://solar-pv-nowcasting-data/PV/Passive/ocf_formatted/v0/system_metadata_OCF_ONLY.csv
    history_minutes: 60
    forecast_minutes: 120
    time_resolution_minutes: 5
    start_datetime: "2020-01-01T00:00:00"
    end_datetime: "2021-09-01T00:00:00"
    pv_image_size_meters_height: 24
    pv_image_size_meters_width: 24
    n_pv_systems_per_example: 128
    get_center: false
    is_live: false

  satellite:
    satellite_zarr_path: gs://solar-pv-nowcasting-data/satellite/EUMETSAT/SEVIRI_RSS/v4/2020_nonhrv.zarr
    history_minutes: 60
    forecast_minutes: 0
    time_resolution_minutes: 5
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels_height: 24
    satellite_image_size_pixels_width: 24
    satellite_meters_per_pixel: 6000
    keep_dawn_dusk_hours: 4
    live_delay_minutes: 30
    is_live: false
    log_level: DEBUG

  hrvsatellite:
    hrvsatellite_zarr_path: gs://solar-pv-nowcasting-data/satellite/EUMETSAT/SEVIRI_RSS/v4/2020_hrv.zarr
    history_minutes: 60
    forecast_minutes: 0
    time_resolution_minutes: 5
    hrvsatellite_channels:
      - HRV
    hrvsatellite_image_size_pixels_height: 128
    hrvsatellite_image_size_pixels_width: 256

  topographic:
    topographic_filename: gs://solar-pv-nowcasting-data/Topographic/europe_dem_1km_osgb.tif
    topographic_image_size_pixels_width: 300
    topographic_image_size_pixels_height: 300

output_data:
  filepath: "not-needed"
